// Curated candidate pool for AI-reasoned role matching — no live job-board API,
// per spec. The model picks and ranks from this list, it doesn't invent titles.
export const ROLE_ARCHETYPES = [
  "Frontend Engineer",
  "Senior Frontend Engineer",
  "Backend Engineer",
  "Full-Stack Engineer",
  "Senior Full-Stack Engineer",
  "Mobile Engineer (iOS)",
  "Mobile Engineer (Android)",
  "React Native Engineer",
  "DevOps Engineer",
  "Site Reliability Engineer",
  "Platform Engineer",
  "Cloud Infrastructure Engineer",
  "Data Engineer",
  "Data Scientist",
  "Machine Learning Engineer",
  "AI/ML Research Engineer",
  "QA / Test Automation Engineer",
  "Engineering Manager",
  "Technical Lead",
  "Staff Engineer",
  "Principal Engineer",
  "Solutions Architect",
  "Product Engineer",
  "Growth Engineer",
  "Developer Experience Engineer",
  "Design Systems Engineer",
  "UI Engineer",
  "UX Engineer",
  "Performance Engineer",
  "Security Engineer",
  "Blockchain / Web3 Engineer",
  "Game Developer",
  "Embedded Systems Engineer",
  "Technical Product Manager",
  "Developer Advocate",
  "Technical Writer",
  "Database Administrator",
  "Analytics Engineer",
  "Integrations Engineer",
  "API Engineer",
  "Founding Engineer (Startup)",
] as const;
